# Generated by Django 6.1 on 2026-09-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Truck Categories',
            },
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='trucks/')),
                ('brochure_pdf', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('range_km', models.IntegerField(help_text='Range per charge in KM')),
                ('payload_capacity_kg', models.IntegerField(help_text='Payload in KG')),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fast_charge_time', models.CharField(max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='fleet.truckcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('truck_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truckmodel')),
            ],
        ),
    ]
