# Generated by Django 6.1 on 2026-09-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='charging_port',
            field=models.CharField(default='CCS2', max_length=50),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 6250mm x 2350mm x 3124mm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='drive_mode',
            field=models.CharField(blank=True, help_text='e.g. 4x2 / 4x4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='max_speed',
            field=models.CharField(blank=True, help_text='e.g. 90 km/h', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='motor_peak_power',
            field=models.CharField(blank=True, help_text='e.g. 130 kW', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='motor_torque',
            field=models.CharField(blank=True, help_text='e.g. 850 Nm', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='wheelbase',
            field=models.CharField(blank=True, help_text='e.g. 3300mm', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='battery_capacity_kwh',
            field=models.DecimalField(decimal_places=2, help_text='e.g. 98.04 or 105.28', max_digits=6),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='fast_charge_time',
            field=models.CharField(default='2 hrs (DC Fast)', max_length=50),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='payload_capacity_kg',
            field=models.IntegerField(help_text='Payload in KG, e.g. 7200'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='range_km',
            field=models.CharField(help_text='e.g. 210 km or 250-350 km', max_length=50),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
