# Generated by Django 6.1 on 2026-09-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_truckmodel_charging_port_truckmodel_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='exterior_image',
            field=models.ImageField(blank=True, help_text='Full exterior vehicle photo', null=True, upload_to='trucks/exterior/'),
        ),
        migrations.AddField(
            model_name='truckmodel',
            name='interior_image',
            field=models.ImageField(blank=True, help_text='Cabin / Interior view photo', null=True, upload_to='trucks/interior/'),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='trucks/main/'),
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trucks/gallery/')),
                ('caption', models.CharField(blank=True, help_text='e.g. Digital Dashboard Display', max_length=150)),
                ('image_type', models.CharField(choices=[('exterior', 'Exterior View'), ('interior', 'Interior / Cabin'), ('spec', 'Technical Diagram / Spec')], default='exterior', max_length=20)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='fleet.truckmodel')),
            ],
        ),
    ]
