# Generated by Django 6.1 on 2026-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_truckmodel_exterior_image_truckmodel_interior_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmodel',
            name='price',
            field=models.CharField(default='Contact for Price', max_length=100),
        ),
    ]
