# Generated by Django 6.1 on 2026-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_truckmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmodel',
            name='exterior_image',
            field=models.CharField(blank=True, help_text="e.g. 'fleet/images/electric-truck.png'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='interior_image',
            field=models.CharField(blank=True, help_text="e.g. 'fleet/images/inside-truck.png'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckmodel',
            name='main_image',
            field=models.CharField(default='fleet/images/5_step_truck.png', help_text="Relative static path, e.g. 'fleet/images/4T_dayun.png'", max_length=255),
        ),
    ]
